import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/app/components/footer/footer";
import Navbar from "@/app/components/main/navbar/navbar";
import FloatingPhoneCTA from "@/app/components/main/FloatingPhoneCTA/FloatingPhoneCTA";
import useSmoothScroll from '/components/smoothScroll/SmoothScroll'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const containerRef = useSmoothScroll()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        ref={containerRef}
      >
      <Navbar></Navbar>
      <FloatingPhoneCTA></FloatingPhoneCTA>
        {children}
      <Footer></Footer>
      </body>
    </html>
  );
}
